global using Microsoft.JSInterop;
global using System.ComponentModel;
global using Microsoft.AspNetCore.Mvc;
global using LearnBlazor.Components.Pages;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Localization;
global using Microsoft.Extensions.FileProviders;
global using Microsoft.AspNetCore.Components.Web;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.EntityFrameworkCore.Infrastructure;

global using LearnBlazor.Data;
global using LearnBlazor.Models;
global using LearnBlazor.Locales;
global using LearnBlazor.Services;
global using LearnBlazor.Components;
global using LearnBlazor.Repository;
global using LearnBlazor.Components.Base;